ALTER TABLE journal
  MODIFY COLUMN message BLOB DEFAULT NULL,
  ADD COLUMN event BLOB DEFAULT NULL,
  ADD COLUMN event_manifest VARCHAR(255) DEFAULT NULL,
  ADD COLUMN ser_id INTEGER DEFAULT NULL,
  ADD COLUMN ser_manifest VARCHAR(255) DEFAULT NULL,
  ADD COLUMN writer_uuid VARCHAR(36) DEFAULT NULL;

ALTER TABLE snapshot
  MODIFY COLUMN snapshot BLOB DEFAULT NULL,
  ADD COLUMN snapshot_data BLOB DEFAULT NULL,
  ADD COLUMN ser_id INTEGER DEFAULT NULL,
  ADD COLUMN ser_manifest VARCHAR(255) DEFAULT NULL;