# Config for https://github.com/release-drafter/release-drafter
name-template: 'Akka Persistence JDBC $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🚀 Enhancements'
    label: 'enhancement'
  - title: 'Dependency changes'
    label: 'dependency-change'

change-template: '- $TITLE [#$NUMBER](https://github.com/akka/akka-persistence-jdbc/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'

template: |
  ## Changes

  $CHANGES

  ## Credits

  This release includes contributions from $CONTRIBUTORS – thank you all very much!

  The Akka core team is employed by [Lightbend](https://www.lightbend.com/). If you’re looking [to take your Akka systems to the next level](https://www.lightbend.com/lightbend-subscription), let’s [set up a time](https://lightbend.com/contact) to discuss our enterprise-grade expert support, self-paced education courses, and technology enhancements that help you manage, monitor and secure your Akka systems - from development to production.
