ALTER TABLE public.journal
  ALTER COLUMN message DROP NOT NULL,
  ALTER COLUMN message SET DEFAULT NULL,
  ADD COLUMN event BYTEA DEFAULT NULL,
  ADD COLUMN event_manifest VARCHAR(255) DEFAULT NULL,
  ADD COLUMN ser_id INTEGER DEFAULT NULL,
  ADD COLUMN ser_manifest VARCHAR(255) DEFAULT NULL,
  ADD COLUMN writer_uuid VARCHAR(36) DEFAULT NULL;

ALTER TABLE public.snapshot
  ALTER COLUMN snapshot DROP NOT NULL,
  ALTER COLUMN snapshot SET DEFAULT NULL,
  ADD COLUMN snapshot_data BYTEA DEFAULT NULL,
  ADD COLUMN ser_id INTEGER DEFAULT NULL,
  ADD COLUMN ser_manifest VARCHAR(255) DEFAULT NULL;