name: Release Drafter

on:
  push:
    branches:
    - master
    - main
    - release-*

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-persistence-jdbc'
    permissions:
      contents: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      # https://github.com/release-drafter/release-drafter/releases
      # v5.21.1
      - uses: release-drafter/release-drafter@6df64e4ba4842c203c604c1f45246c5863410adb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
