name: Release

on:
  push:
    branches:
      - snapshot-release
    tags: ["*"]

jobs:
  release:
    # runs on main repo only
    if: github.repository == 'akka/akka-persistence-jdbc'
    name: Release
    # the release environment provides access to secrets required in the release process
    # https://github.com/akka/akka-persistence-jdbc/settings/environments/164872635/edit
    environment: release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 8
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Publish artifacts for all Scala versions
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: sbt ci-release
