name: SqlServer Integration Tests

on:
  pull_request:
  push:
    branches:
      - main
      - master
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
   integration-test:
    name: Integration Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "SqlServer", extraOpts: '' }
          - { name: "SqlServer (old dao)", extraOpts: ' -Djdbc-journal.dao=akka.persistence.jdbc.journal.dao.legacy.ByteArrayJournalDao -Djdbc-snapshot-store.dao=akka.persistence.jdbc.snapshot.dao.legacy.ByteArraySnapshotDao -Djdbc-read-journal.dao=akka.persistence.jdbc.query.dao.legacy.ByteArrayReadJournalDao' }
          
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.11.0

      - name: Start docker
        run: ./scripts/launch-sqlserver.sh

      - name: Run Integration tests for  ${{ matrix.name }}
        run: sbt "integration/testOnly akka.persistence.jdbc.integration.SqlServer*"  ${{ matrix.extraOpts }} -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
