name: Weekly Integration Tests

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-test:
    name: Weekly Integration Test ${{ matrix.db.name }}, ${{ matrix.db.jdk }}
    runs-on: Akka-Default
    strategy:
      fail-fast: false
      matrix:
        db:
          - name: "H2"
            test: "test"
            jdk: 'temurin:1.21'
          - name: "H2"
            test: "test"
            jdk: 'temurin:1.25'
          - name: "MySQL"
            test: '"integration/testOnly akka.persistence.jdbc.integration.MySQL*"'
            script: 'launch-mysql.sh'
            jdk: 'temurin:1.21'
          - name: "Oracle"
            test: '"integration/testOnly akka.persistence.jdbc.integration.Oracle*"'
            script: 'launch-oracle.sh'
            jdk: 'temurin:1.21'
          - name: "Postgres"
            test: '"integration/testOnly akka.persistence.jdbc.integration.Postgres*"'
            script: 'launch-postgres.sh'
            jdk: 'temurin:1.21'
          - name: "SqlServer"
            test: '"integration/testOnly akka.persistence.jdbc.integration.SqlServer*"'
            script: 'launch-sqlserver.sh'
            jdk: 'temurin:1.21'

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up ${{ matrix.db.jdk }}
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: ${{ matrix.db.jdk }}

      - name: Run akka/github-actions-scripts
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Start DB in docker container
        if: ${{ matrix.db.script }}
        run: |-
          ./scripts/${{ matrix.db.script }}

      - name: Run Integration tests for  ${{ matrix.db.name }}
        run: sbt ${{ matrix.db.test }}

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
